import { Button } from "@mui/material";
import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Tech Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/> */}
      </Head>
      <video
        src={`/api/videos?videoId=ss`}
        width="800px"
        height="auto"
        controls
        autoPlay
        id="video-player"
      />
      <div className="text-red-600 font-bold flex justify-center flex-col">
        <h1 className="text-center p-4">Home Page</h1>
        <Button
          className="m-4"
          color="primary"
          type="submit"
          variant="outlined"
          onClick={() => router.push("/user/login")}
        >
          User Login
        </Button>
        <Button
          className="m-4"
          color="primary"
          type="submit"
          variant="outlined"
          onClick={() => router.push("/blogs")}
        >
          Blogs
        </Button>
        <Button
          className="m-4"
          color="primary"
          type="submit"
          variant="outlined"
          onClick={() => router.push("/blogs/add-blog")}
        >
          Add Blogs
        </Button>

        <Button
          className="m-4"
          color="primary"
          type="submit"
          variant="outlined"
          onClick={() => router.push("/message")}
        >
          Contact Us
        </Button>
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: { query: context.query },
  };
};
